### ISSUE TITLE
Espaciado entre párrafos demasiado grande

### ISSUE THREAD

**Issue by martinvol** [PartidoDeLaRed/asamblea#14]
Siempre que en mis propuestas pongo un fin de linea (\n) queda un espaciado muy grande entre los párrafos.

``` css
article.proposal .clauses .clause {
    margin-bottom: 20px;
}
```

Creo que esa es la propiedad debería estar en 0.
